[features]
seeds = false
[programs.localnet]
donation_solana = "3vKFQUmdGGiHR6hK3tQ1JJnD3YCF4b4ktDUutgCsgScG"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/valeri/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
